### ISSUE TITLE
Hubspot subject is not getting reflected

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-hubspot#12]
### Expected Behavior

"subject" attribute of the Hubspot create ticket task should be used as ticket name.

### Actual Behaviour

"subject" attribute of the Hubspot create ticket task should be used as ticket name. Instead, "content" is appearing as ticket name.

<img width="1728" alt="Screenshot 2024-09-21 at 8 33 15 AM" src="https://github.com/user-attachments/assets/84665d4e-be4b-4f4a-926f-00c7bf75071f">

### Steps To Reproduce

1. Run the flow in the example.
2. Expecting "Workflow failed" to be the ticket name. Instead `content` appears in the ticket name.
("content" also appears in the ticket description as expected.)

### Environment Information

- Kestra Version: 0.18.1
- Plugin version: 0.18.1
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```yaml
id: hubspot_flow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.hubspot.tickets.Create
    apiKey: pat-na1-ad40cfe0-3f07-484d-b64d-8ecc1df0b8fe
    subject: Workflow failed
    content: "Alert! Kestra workflow failed! {{ execution.id }} has failed on {{ taskrun.startDate }}"
    stage: 3
    priority: HIGH
```
